// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZgFb2tF5c4USp0W5a7ZeSCOAIgxIezY',
    appId: '1:976058875224:web:57e9c16ce1597f0ee0f92d',
    messagingSenderId: '976058875224',
    projectId: 'chantiertrack-561bf',
    authDomain: 'chantiertrack-561bf.firebaseapp.com',
    storageBucket: 'chantiertrack-561bf.firebasestorage.app',
    measurementId: 'G-130TJ76X4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNN8v8NVgWBqY2A8eiQ4IXCGRj8nvHM8',
    appId: '1:976058875224:android:967f47b3c4ab470ce0f92d',
    messagingSenderId: '976058875224',
    projectId: 'chantiertrack-561bf',
    storageBucket: 'chantiertrack-561bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRcnfPFqSMkcJMU5hyXBPtUQ5Ss80hxcc',
    appId: '1:976058875224:ios:1e882014ebd1d839e0f92d',
    messagingSenderId: '976058875224',
    projectId: 'chantiertrack-561bf',
    storageBucket: 'chantiertrack-561bf.firebasestorage.app',
    iosBundleId: 'com.example.chantierTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRcnfPFqSMkcJMU5hyXBPtUQ5Ss80hxcc',
    appId: '1:976058875224:ios:1e882014ebd1d839e0f92d',
    messagingSenderId: '976058875224',
    projectId: 'chantiertrack-561bf',
    storageBucket: 'chantiertrack-561bf.firebasestorage.app',
    iosBundleId: 'com.example.chantierTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVZgFb2tF5c4USp0W5a7ZeSCOAIgxIezY',
    appId: '1:976058875224:web:db53e86374a6a9a1e0f92d',
    messagingSenderId: '976058875224',
    projectId: 'chantiertrack-561bf',
    authDomain: 'chantiertrack-561bf.firebaseapp.com',
    storageBucket: 'chantiertrack-561bf.firebasestorage.app',
    measurementId: 'G-E6VSC1TPV4',
  );
}
